FROM python:3.9-buster

# ALSA ライブラリ依存関係をインストール
RUN apt-get update && apt-get install -y \
    libsndfile1 \
    libasound2-dev \
    portaudio19-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*
    pip install boto3
    pip install python-dotenv

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app/ .

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]